-- Hilfetexte nachgezogen: fehlender Bereich und zweite Absaetze (#276)
INSERT INTO translations (lang, tkey, value) VALUES
('en','help_mailversand','Who may send mail in the band''s name, that is, reply in the mailbox. Kept apart from reading it: whoever sees the enquiries need not be the one who answers. The access details for a new member do not depend on it — those belong to creating an account.'),
('nl','help_mailversand','Wie namens de band mail mag versturen, dus in het postvak mag antwoorden. Los van het lezen: wie de aanvragen ziet, hoeft niet degene te zijn die antwoordt. De toegangsgegevens voor een nieuw lid hangen er niet van af — die horen bij het aanmaken van een account.'),
('fr','help_mailversand','Qui peut envoyer du courrier au nom du groupe, c''est-à-dire répondre dans la boîte mail. Distinct de la lecture : celui qui voit les demandes n''est pas forcément celui qui répond. Les accès d''un nouveau membre n''en dépendent pas — ils font partie de la création du compte.'),
('es','help_mailversand','Quién puede enviar correo en nombre de la banda, es decir, responder en el buzón. Separado de la lectura: quien ve las solicitudes no tiene por qué ser quien responde. Los datos de acceso de un nuevo miembro no dependen de ello: forman parte de crear la cuenta.'),
('it','help_mailversand','Chi può inviare posta a nome della band, cioè rispondere nella casella. Separato dalla lettura: chi vede le richieste non deve per forza essere chi risponde. I dati di accesso di un nuovo membro non ne dipendono: fanno parte della creazione dell''account.'),
('en','help_mitglieder_2','Creating an account mails the access details to the new member; the start password in it is good for seven days and has to be changed at the first sign-in. If that mail never arrived, "Send access details" sits next to the account — it makes a new start password and voids the old one, which is why the button only appears for accounts that have never signed in. Rights are granted per area; the treasury and the mailbox have to be given even to an admin.'),
('nl','help_mitglieder_2','Bij het aanmaken gaat een mail met de toegangsgegevens naar het nieuwe lid; het startwachtwoord daarin geldt zeven dagen en moet bij de eerste aanmelding worden gewijzigd. Kwam die mail nooit aan, dan staat er "Toegangsgegevens sturen" naast het account — dat maakt een nieuw startwachtwoord en maakt het oude ongeldig, daarom verschijnt de knop alleen bij accounts die zich nog nooit hebben aangemeld. Rechten worden per gebied gegeven; kas en postvak moet ook een beheerder uitdrukkelijk krijgen.'),
('fr','help_mitglieder_2','À la création, un courriel avec les accès part vers le nouveau membre ; le mot de passe initial vaut sept jours et doit être changé à la première connexion. Si ce courriel n''est jamais arrivé, « Envoyer les accès » figure à côté du compte — cela crée un nouveau mot de passe initial et annule l''ancien, c''est pourquoi le bouton n''apparaît que pour les comptes jamais connectés. Les droits se donnent par domaine ; la caisse et la boîte mail doivent être accordées même à un administrateur.'),
('es','help_mitglieder_2','Al crear la cuenta se envía un correo con los datos de acceso al nuevo miembro; la contraseña inicial vale siete días y debe cambiarse en el primer inicio de sesión. Si ese correo nunca llegó, junto a la cuenta aparece "Enviar datos de acceso": genera una contraseña inicial nueva y anula la anterior, por eso el botón solo aparece en cuentas que nunca han iniciado sesión. Los permisos se dan por área; la caja y el buzón hay que concedérselos incluso a un administrador.'),
('it','help_mitglieder_2','Alla creazione parte una mail con i dati di accesso verso il nuovo membro; la password iniziale vale sette giorni e va cambiata al primo accesso. Se quella mail non è mai arrivata, accanto all''account compare "Invia i dati di accesso": crea una nuova password iniziale e annulla la vecchia, per questo il pulsante appare solo per account che non hanno mai effettuato l''accesso. I permessi si danno per area; cassa e casella di posta vanno concesse anche a un amministratore.'),
('en','help_post_2','The mailbox has to be granted explicitly, to an administrator as well: it holds enquiries, invoices and private replies, and running the application is no reason to read along. Replying additionally requires the "sending mail" right.'),
('nl','help_post_2','Het postvak moet uitdrukkelijk worden gegeven, ook aan een beheerder: daar liggen aanvragen, facturen en persoonlijke antwoorden, en de toepassing beheren is geen reden om mee te lezen. Antwoorden vraagt bovendien het recht "mail versturen".'),
('fr','help_post_2','La boîte mail doit être accordée explicitement, à un administrateur aussi : on y trouve des demandes, des factures et des réponses privées, et administrer l''application n''est pas une raison de les lire. Répondre exige en plus le droit « envoi de courrier ».'),
('es','help_post_2','El buzón hay que concederlo expresamente, también a un administrador: allí hay solicitudes, facturas y respuestas privadas, y administrar la aplicación no es motivo para leerlas. Responder exige además el permiso "envío de correo".'),
('it','help_post_2','La casella va concessa espressamente, anche a un amministratore: vi si trovano richieste, fatture e risposte private, e amministrare l''applicazione non è un motivo per leggerle. Rispondere richiede inoltre il diritto "invio di posta".'),
('en','help_setlists_2','For the printout you choose what comes along: artist, year, tempo, playing time and the note — first line or in full. The type size fits itself to the paper. The teleprompter also starts from the setlist and moves on by itself at the end of a song to the next one that has lyrics.'),
('nl','help_setlists_2','Voor de afdruk kies je wat meegaat: artiest, jaar, tempo, speelduur en de notitie — eerste regel of volledig. De lettergrootte past zich aan het blad aan. Ook de teleprompter start vanuit de setlist en gaat aan het eind van een nummer vanzelf door naar het volgende met songtekst.'),
('fr','help_setlists_2','Pour l''impression, vous choisissez ce qui figure : interprète, année, tempo, durée et la note — première ligne ou entière. La taille des caractères s''ajuste à la feuille. Le prompteur démarre aussi depuis la setlist et passe de lui-même, à la fin d''un morceau, au suivant qui a des paroles.'),
('es','help_setlists_2','Para la impresión eliges qué se incluye: intérprete, año, tempo, duración y la nota, primera línea o completa. El tamaño de letra se ajusta a la hoja. El teleprónter también arranca desde la lista y pasa por sí solo, al terminar una canción, a la siguiente que tenga letra.'),
('it','help_setlists_2','Per la stampa scegli cosa includere: interprete, anno, tempo, durata e la nota, prima riga o intera. La dimensione del carattere si adatta al foglio. Anche il gobbo parte dalla scaletta e passa da solo, a fine brano, al successivo che ha un testo.')
ON DUPLICATE KEY UPDATE value = value;
