-- Hilfe nachgetragen: Supportact, Ort im Kalender, Bilder aus der Galerie, Rider-Druck,
-- Mitglieder ohne Adresse, Gäste ohne Adresse und Bewertung (#298)
INSERT INTO translations (lang, tkey, value) VALUES
('en','help_termine_3','If another band plays that evening — as your opener, or you are theirs — enter it on the gig under "Support act". The name then appears in the event line, in the calendar subscription and in the table you can download. It deliberately does not appear on the public page: an opener that is not confirmed yet should not end up on the internet by itself.'),
('en','help_orte_2','When a venue is linked to an event, its full address also appears in the calendar subscription and on the public page — not just the town from the free-text field. The calendar entry also carries a navigation link that opens directions to the venue on a phone.'),
('en','help_fotos_2','A picture from the gallery can become the logo, the background, the browser icon or the picture next to the greeting: in the settings under "Logo & background" there is "Take from the media", and every gallery picture has a "use as" button. The other way round, everything uploaded there also lands in the gallery, with a matching tag so you find it again. The picture is copied: delete it in the gallery and the logo stays.'),
('en','help_rider_2','When printed, the stage plan and the channel list each start on a page of their own — the two sheets a sound engineer pins to the mixing desk. If you have booked a guest for a gig, a sound engineer for instance, they see the same rider through their invitation link.'),
('en','help_mitglieder_3','A member may be added without an email address — the line-up is often settled before all addresses are. Such an account cannot sign in yet; the list says "No access — email address missing". As soon as you enter the address under "Edit", the invitation goes out by itself. The same happens when you correct the address of a member who has never signed in — the old one was probably mistyped. Below the account you then see what became of the invitation: "delivered", or "refused" with the reason the mail provider gave. If it only says "handed over", the server does not know the outcome yet.'),
('en','help_gaeste_2','If a guest has no email address, no invitation is sent — the booking is created anyway, and the event shows a "Link" button. Copy it and send it any way you like, as a message to their phone for instance; for the guest the link is the same as the mail. If you add the address later, "Resend invitation" appears. After the show you can rate the guest, one to five stars and a line about it; the guest list shows the average. The guest never sees this rating — and through their link only what belongs to their event: no other events, no members, no money.'),

('nl','help_termine_3','Speelt die avond nog een andere band — als jullie voorprogramma, of jullie zijn dat van hen — dan vul je die bij het optreden in onder „Voorprogramma". De naam staat dan in de regel van de datum, in het agenda-abonnement en in de tabel om te downloaden. Op de openbare pagina verschijnt hij bewust niet: een voorprogramma dat nog niet vaststaat, hoort niet vanzelf op internet.'),
('nl','help_orte_2','Is een locatie aan een datum gekoppeld, dan staat het volledige adres ook in het agenda-abonnement en op de openbare agendapagina — niet alleen de plaatsnaam uit het vrije tekstveld. In de agenda-afspraak zit bovendien een navigatielink die op de telefoon meteen de route opent.'),
('nl','help_fotos_2','Een afbeelding uit de galerij kan logo, achtergrond, browsersymbool of het plaatje naast de begroeting worden: in de instellingen onder „Logo & achtergrond" staat „Uit de media overnemen", en bij elke afbeelding in de galerij de knop „gebruiken als". Omgekeerd komt alles wat je daar uploadt ook in de galerij, met een passend trefwoord zodat je het terugvindt. De afbeelding wordt gekopieerd: verwijder je haar in de galerij, dan blijft het logo staan.'),
('nl','help_rider_2','Bij het afdrukken beginnen podiumplan en kanaallijst elk op een eigen pagina — de twee bladen die de geluidstechnicus aan de mengtafel hangt. Heb je voor een optreden een gast geboekt, bijvoorbeeld een geluidstechnicus, dan ziet die dezelfde rider via zijn uitnodigingslink.'),
('nl','help_mitglieder_3','Een lid mag ook zonder e-mailadres worden aangemaakt — de bezetting staat vaak vast voordat alle adressen er zijn. Zo een account kan nog niet inloggen; in de lijst staat „Geen toegang — e-mailadres ontbreekt". Zodra je het adres onder „Bewerken" invult, gaat de uitnodiging vanzelf uit. Hetzelfde gebeurt als je bij een lid dat nog nooit heeft ingelogd het adres corrigeert — het oude was dan waarschijnlijk verkeerd getypt. Onder het account zie je daarna wat er van de uitnodiging werd: „bezorgd", of „geweigerd" met de reden die de mailprovider gaf. Staat er alleen „overgedragen", dan kent de server de uitkomst nog niet.'),
('nl','help_gaeste_2','Heeft een gast geen e-mailadres, dan gaat er geen uitnodiging uit — de boeking ontstaat toch, en bij de datum staat een knop „Link". Die kopieer je en stuur je zoals je wilt, bijvoorbeeld als bericht naar de telefoon; voor de gast is de link hetzelfde als de mail. Vul je het adres later in, dan verschijnt „Uitnodiging opnieuw sturen". Na het optreden kun je de gast beoordelen, één tot vijf sterren en een regel erbij; in de gastenlijst zie je het gemiddelde. De gast ziet die beoordeling nooit — en via zijn link ook alleen wat bij zijn datum hoort: geen andere data, geen leden, geen kas.'),

('fr','help_termine_3','Si un autre groupe joue ce soir-là — en première partie, ou c''est vous qui l''êtes —, indiquez-le sur le concert sous « Première partie ». Le nom apparaît alors dans la ligne de la date, dans l''abonnement au calendrier et dans le tableau à télécharger. Il n''apparaît volontairement pas sur la page publique : une première partie pas encore confirmée ne doit pas se retrouver sur internet toute seule.'),
('fr','help_orte_2','Quand un lieu est lié à une date, son adresse complète figure aussi dans l''abonnement au calendrier et sur la page publique des dates — pas seulement la ville du champ libre. L''entrée du calendrier contient de plus un lien de navigation qui ouvre l''itinéraire sur le téléphone.'),
('fr','help_fotos_2','Une image de la galerie peut devenir le logo, le fond, l''icône du navigateur ou l''image à côté de la salutation : dans les réglages, sous « Logo & fond », il y a « Reprendre depuis les médias », et chaque image de la galerie a un bouton « utiliser comme ». Inversement, tout ce que vous téléversez là arrive aussi dans la galerie, avec un mot-clé pour le retrouver. L''image est copiée : supprimez-la dans la galerie, le logo reste.'),
('fr','help_rider_2','À l''impression, le plan de scène et la liste des canaux commencent chacun sur une page à part — les deux feuilles que l''ingénieur du son accroche à la console. Si vous avez réservé un invité pour un concert, un ingénieur du son par exemple, il voit le même rider par son lien d''invitation.'),
('fr','help_mitglieder_3','Un membre peut être ajouté sans adresse e-mail — la formation est souvent fixée avant que toutes les adresses soient là. Un tel compte ne peut pas encore se connecter ; la liste indique « Pas d''accès — adresse e-mail manquante ». Dès que vous saisissez l''adresse sous « Modifier », l''invitation part toute seule. Il en va de même si vous corrigez l''adresse d''un membre qui ne s''est jamais connecté — l''ancienne était sans doute mal écrite. Sous le compte, vous voyez ensuite ce qu''est devenue l''invitation : « livrée », ou « refusée » avec la raison donnée par le fournisseur de mail. S''il n''y a que « remise », le serveur ne connaît pas encore le résultat.'),
('fr','help_gaeste_2','Si un invité n''a pas d''adresse e-mail, aucune invitation ne part — la réservation est créée quand même, et la date affiche un bouton « Lien ». Copiez-le et envoyez-le comme vous voulez, par message sur le téléphone par exemple ; pour l''invité, le lien vaut la mail. Si vous ajoutez l''adresse plus tard, « Renvoyer l''invitation » apparaît. Après le concert, vous pouvez noter l''invité, une à cinq étoiles et une ligne ; la liste des invités montre la moyenne. L''invité ne voit jamais cette note — et par son lien seulement ce qui concerne sa date : pas d''autres dates, pas de membres, pas de caisse.'),

('es','help_termine_3','Si esa noche toca otra banda —como vuestros teloneros, o vosotros sois los suyos—, anotadla en la actuación bajo «Telonero». El nombre aparece entonces en la línea de la fecha, en la suscripción al calendario y en la tabla para descargar. En la página pública no aparece a propósito: un telonero aún sin confirmar no debe acabar solo en internet.'),
('es','help_orte_2','Si un lugar está vinculado a una fecha, su dirección completa aparece también en la suscripción al calendario y en la página pública de fechas, no solo la ciudad del campo de texto libre. La entrada del calendario lleva además un enlace de navegación que abre la ruta en el móvil.'),
('es','help_fotos_2','Una imagen de la galería puede convertirse en logo, fondo, icono del navegador o imagen junto al saludo: en los ajustes, bajo «Logo y fondo», está «Tomar de los medios», y cada imagen de la galería tiene el botón «usar como». Al revés, todo lo que subís allí llega también a la galería, con una etiqueta para encontrarlo. La imagen se copia: si la borráis en la galería, el logo se queda.'),
('es','help_rider_2','Al imprimir, el plano de escenario y la lista de canales empiezan cada uno en su propia página: las dos hojas que el técnico de sonido cuelga en la mesa. Si habéis reservado un invitado para una actuación, un técnico de sonido por ejemplo, ve el mismo rider a través de su enlace de invitación.'),
('es','help_mitglieder_3','Un miembro puede añadirse sin dirección de correo: la formación suele estar decidida antes de tener todas las direcciones. Esa cuenta aún no puede iniciar sesión; la lista dice «Sin acceso: falta la dirección de correo». En cuanto introducís la dirección en «Editar», la invitación sale sola. Lo mismo ocurre si corregís la dirección de un miembro que nunca ha iniciado sesión: la anterior seguramente estaba mal escrita. Debajo de la cuenta veis después qué fue de la invitación: «entregada», o «rechazada» con el motivo que dio el proveedor de correo. Si solo dice «entregada al servidor», el servidor aún no conoce el resultado.'),
('es','help_gaeste_2','Si un invitado no tiene correo, no sale invitación; la reserva se crea igual y en la fecha aparece un botón «Enlace». Lo copiáis y lo enviáis como queráis, por mensaje al móvil por ejemplo; para el invitado el enlace vale lo mismo que el correo. Si añadís la dirección después, aparece «Reenviar invitación». Tras la actuación podéis valorar al invitado, de una a cinco estrellas y una línea; la lista de invitados muestra la media. El invitado nunca ve esa valoración, y por su enlace solo lo que pertenece a su fecha: ni otras fechas, ni miembros, ni la caja.'),

('it','help_termine_3','Se quella sera suona un''altra band — come vostro gruppo spalla, o siete voi il loro —, indicatela sul concerto sotto «Supporto». Il nome compare allora nella riga della data, nell''abbonamento al calendario e nella tabella da scaricare. Sulla pagina pubblica non compare di proposito: un gruppo spalla non ancora confermato non deve finire da solo in internet.'),
('it','help_orte_2','Se un luogo è collegato a una data, il suo indirizzo completo compare anche nell''abbonamento al calendario e sulla pagina pubblica delle date, non solo la città del campo libero. La voce del calendario porta inoltre un link di navigazione che sul telefono apre subito il percorso.'),
('it','help_fotos_2','Un''immagine della galleria può diventare logo, sfondo, icona del browser o immagine accanto al saluto: nelle impostazioni, sotto «Logo e sfondo», c''è «Prendi dai media», e ogni immagine della galleria ha il pulsante «usa come». All''inverso, tutto ciò che caricate lì finisce anche nella galleria, con un tag per ritrovarlo. L''immagine viene copiata: se la cancellate nella galleria, il logo resta.'),
('it','help_rider_2','In stampa, il piano palco e la lista canali iniziano ciascuno su una pagina propria — i due fogli che il fonico appende al mixer. Se avete prenotato un ospite per un concerto, un fonico ad esempio, vede lo stesso rider tramite il suo link d''invito.'),
('it','help_mitglieder_3','Un membro può essere aggiunto anche senza indirizzo e-mail — la formazione spesso è decisa prima di avere tutti gli indirizzi. Un account così non può ancora accedere; nella lista c''è «Nessun accesso: manca l''indirizzo e-mail». Appena inserite l''indirizzo in «Modifica», l''invito parte da solo. Lo stesso accade se correggete l''indirizzo di un membro che non ha mai effettuato l''accesso: quello vecchio era probabilmente scritto male. Sotto l''account vedete poi cosa è successo all''invito: «recapitato», oppure «rifiutato» con il motivo dato dal provider di posta. Se c''è solo «consegnato al server», il server non conosce ancora l''esito.'),
('it','help_gaeste_2','Se un ospite non ha un indirizzo e-mail, non parte alcun invito — la prenotazione si crea comunque e alla data compare un pulsante «Link». Lo copiate e lo inviate come volete, ad esempio come messaggio sul telefono; per l''ospite il link vale quanto la mail. Se aggiungete l''indirizzo più tardi, compare «Invia di nuovo l''invito». Dopo il concerto potete valutare l''ospite, da una a cinque stelle con una riga; la lista ospiti mostra la media. L''ospite non vede mai questa valutazione — e tramite il suo link solo ciò che riguarda la sua data: nessun''altra data, nessun membro, nessuna cassa.')
ON DUPLICATE KEY UPDATE value = value;
