-- Help texts brought back in line with what the application actually does
-- (EN/NL/FR/ES/IT), plus the two new ones: the count on the app icon and
-- signing in without a password.
--
-- The German originals of app_install_offline, app_install_push, help_songs,
-- help_orte and help_fotos changed, so the stale translations are removed in
-- app/bootstrap.php before this seed runs — INSERT IGNORE only ever adds.
SET NAMES utf8mb4;

INSERT IGNORE INTO translations (lang, tkey, value) VALUES
('en','app_install_offline','Without a signal — the normal case on stage — everything is still there: overview, events, setlists with print views, songs with lyrics, chords and attachments, the rider and the patch list. That is how it comes, so nobody discovers on stage that they took nothing along. If you want less — chords and attachments need space — untick it in your profile under "take offline". Signing out deletes all of it, so nobody finds the previous person''s dates on a shared phone.'),
('en','app_install_push','Notifications to your device live in your profile. All three topics are preselected — new events, new comments, confirmations and cancellations — so you are unticking rather than ticking. Nothing is sent until you register that device there, and the browser asks for permission itself. On iPhone this only works for the installed app. If the section is missing from your profile, the band admin has switched notifications off or the server lacks the prerequisites.'),
('en','app_install_badge','The icon carries a number when something is waiting for you: your open tasks and the coming events you have not answered yet. Notifications that arrived while the app was closed are added. Opening the app clears the notifications from the number — the tasks stay, because a task does not get done by looking at it. On iPhone the app writes the number itself; on Android the system derives it from the notifications in the tray, and whether that shows a number or just a dot is up to the launcher. A device that cannot do it simply has no number.'),
('en','help_songs','The repertoire with key, tempo, length and status. Sheet music, lyrics and recordings hang off the song. For the stage there is a full-screen view: large text, sections set off in colour, scrolling by itself — set the pace with the tempo button, as a number or by tapping the beat. The screen stays awake. Whoever would rather read their own chord sheet switches to it at the top.'),
('en','help_orte','Venues with address, contact and what happened last time. "Find address" has the server fetch the coordinates from OpenStreetMap once and fills in address and town at the same time — this has to be allowed under Settings → Outgoing connections, otherwise the button stays grey. The navigation icon opens your device''s maps app with the destination; on iPhone you pick which one the first time.'),
('en','help_fotos','Pictures for the public page and the archive. On upload the application reads the capture date and location from the file and uses them to suggest which event a photo belongs to — it is only assigned on click. Those details are then removed from the stored file: a rehearsal room is often somebody''s home, and that should not travel with a published photo. Only originals straight from the device carry them at all; anything shared through a messenger lost them long ago.'),
('nl','app_install_offline','Zonder bereik — op podia de normale situatie — is toch alles er: overzicht, afspraken, setlists met printversie, songs met teksten, akkoorden en bijlagen, de rider en de patchlijst. Zo komt het uit de doos, zodat niemand pas op het podium merkt dat hij niets heeft meegenomen. Wil je minder — akkoorden en bijlagen kosten ruimte — vink het dan uit in je profiel onder "offline meenemen". Bij het afmelden wordt alles gewist, zodat niemand op een gedeelde telefoon de afspraken van de vorige vindt.'),
('nl','app_install_push','Meldingen op je apparaat staan in je profiel. Alle drie de onderwerpen staan voorgeselecteerd — nieuwe afspraken, nieuwe reacties, toe- en afzeggingen — je vinkt dus eerder uit dan aan. Er wordt pas iets verstuurd als je je apparaat daar aanmeldt; de browser vraagt daarbij zelf om toestemming. Op de iPhone werkt dat alleen voor de geïnstalleerde app. Staat het onderdeel niet in je profiel, dan heeft het bandbeheer meldingen uitgezet of mist de server de voorwaarden.'),
('nl','app_install_badge','Op het pictogram staat een getal als er iets op je wacht: je openstaande taken en de komende afspraken waarop je nog niet hebt geantwoord. Daar komen meldingen bij die binnenkwamen terwijl de app dicht was. Open je de app, dan verdwijnen de meldingen uit het getal — de taken blijven, want een taak is niet af doordat je ernaar kijkt. Op de iPhone schrijft de app het getal zelf; op Android leidt het systeem het af uit de meldingen in de balk, en of daar een getal of alleen een stip staat, bepaalt het startscherm. Kan een apparaat dat niet, dan ontbreekt alleen het getal.'),
('nl','help_songs','Het repertoire met toonsoort, tempo, duur en status. Bladmuziek, teksten en opnames hangen aan de song. Voor het podium is er een volledig scherm: grote tekst, secties in kleur, en het loopt vanzelf mee — het tempo stel je in met de tempoknop, als getal of door de maat mee te tikken. Het scherm blijft wakker. Wie liever zijn eigen akkoordenblad leest, schakelt daar bovenaan naartoe.'),
('nl','help_orte','Locaties met adres, contactpersoon en ervaringen van de vorige keren. Via "Adres zoeken" haalt de server eenmalig de coördinaten bij OpenStreetMap en vult adres en plaats meteen in — dat moet zijn toegestaan onder Instellingen → Verbindingen naar buiten, anders blijft de knop grijs. Het navigatiesymbool opent de kaartenapp van je apparaat met de bestemming; op de iPhone kies je de eerste keer welke.'),
('nl','help_fotos','Afbeeldingen voor de openbare pagina en het archief. Bij het uploaden leest de toepassing opnamedatum en -locatie uit het bestand en stelt daarmee voor bij welke afspraak een foto hoort — koppelen gebeurt pas op een klik. Daarna worden die gegevens uit het opgeslagen bestand verwijderd: een oefenruimte is vaak een privéadres, en dat hoort niet mee te gaan met een gepubliceerde foto. Alleen originelen rechtstreeks van het apparaat hebben ze; wat via een messenger is gedeeld, is ze allang kwijt.'),
('fr','app_install_offline','Sans réseau — la situation normale sur scène — tout est quand même là : l''aperçu, les dates, les setlists avec leur version imprimable, les morceaux avec paroles, les grilles d''accords et les pièces jointes, la fiche technique et la patch-list. C''est ainsi d''origine, pour que personne ne découvre sur scène qu''il n''a rien emporté. Si tu en veux moins — les accords et les pièces jointes prennent de la place — décoche-le dans ton profil sous « emporter hors ligne ». À la déconnexion, tout est effacé, pour que personne ne retrouve les dates du précédent sur un téléphone partagé.'),
('fr','app_install_push','Les notifications sur ton appareil se règlent dans ton profil. Les trois thèmes sont présélectionnés — nouvelles dates, nouveaux commentaires, confirmations et désistements — tu décoches donc plutôt que tu ne coches. Rien n''est envoyé tant que tu n''as pas enregistré cet appareil ; le navigateur demande lui-même l''autorisation. Sur iPhone, cela ne fonctionne que pour l''app installée. Si la section n''apparaît pas dans ton profil, l''administration du groupe a désactivé les notifications ou le serveur n''a pas les prérequis.'),
('fr','app_install_badge','L''icône porte un chiffre lorsque quelque chose t''attend : tes tâches ouvertes et les dates à venir auxquelles tu n''as pas encore répondu. S''y ajoutent les notifications arrivées pendant que l''app était fermée. En ouvrant l''app, les notifications disparaissent du chiffre — les tâches restent, car une tâche ne se fait pas en la regardant. Sur iPhone, l''app écrit le chiffre elle-même ; sur Android, le système le déduit des notifications dans la barre, et c''est l''écran d''accueil qui décide s''il affiche un chiffre ou seulement un point. Un appareil qui ne sait pas le faire n''a simplement pas de chiffre.'),
('fr','help_songs','Le répertoire avec tonalité, tempo, durée et statut. Partitions, paroles et enregistrements sont rattachés au morceau. Pour la scène, il y a un affichage plein écran : texte en grand, sections en couleur, défilement automatique — le tempo se règle avec le bouton dédié, en chiffre ou en tapant la mesure. L''écran reste allumé. Qui préfère lire sa propre grille d''accords bascule dessus en haut.'),
('fr','help_orte','Les lieux avec adresse, interlocuteur et ce qui s''est passé la dernière fois. Avec « Chercher l''adresse », le serveur récupère une fois les coordonnées auprès d''OpenStreetMap et remplit adresse et ville dans la foulée — cela doit être autorisé sous Réglages → Connexions vers l''extérieur, sinon le bouton reste gris. L''icône de navigation ouvre l''application de cartes de ton appareil avec la destination ; sur iPhone, tu choisis laquelle la première fois.'),
('fr','help_fotos','Des images pour la page publique et pour les archives. Au téléversement, l''application lit la date et le lieu de prise de vue dans le fichier et s''en sert pour proposer à quelle date une photo se rattache — l''association ne se fait qu''au clic. Ces informations sont ensuite retirées du fichier conservé : un local de répétition est souvent un domicile, et cela n''a pas à partir avec une photo publiée. Seuls les originaux venant directement de l''appareil les portent ; ce qui a été partagé par messagerie les a perdues depuis longtemps.'),
('es','app_install_offline','Sin cobertura — lo normal en un escenario — está todo igualmente: resumen, fechas, setlists con su versión imprimible, canciones con letras, acordes y adjuntos, el rider y la lista de canales. Viene así de fábrica, para que nadie descubra en el escenario que no se llevó nada. Si quieres menos — los acordes y los adjuntos ocupan sitio — desmárcalo en tu perfil en "llevar sin conexión". Al cerrar sesión se borra todo, para que en un móvil compartido nadie encuentre las fechas del anterior.'),
('es','app_install_push','Los avisos en tu dispositivo están en tu perfil. Los tres temas vienen marcados — nuevas fechas, nuevos comentarios, confirmaciones y cancelaciones —, así que desmarcas más que marcas. No se envía nada hasta que registres ese dispositivo allí; el navegador pide permiso por su cuenta. En el iPhone solo funciona con la app instalada. Si la sección no aparece en tu perfil, la administración de la banda ha desactivado los avisos o al servidor le faltan los requisitos.'),
('es','app_install_badge','El icono lleva un número cuando algo te espera: tus tareas abiertas y las fechas próximas a las que aún no has respondido. Se suman los avisos que llegaron mientras la app estaba cerrada. Al abrirla, los avisos desaparecen del número — las tareas se quedan, porque una tarea no se hace por mirarla. En el iPhone la app escribe el número ella misma; en Android el sistema lo deduce de los avisos de la barra, y que aparezca un número o solo un punto lo decide la pantalla de inicio. Un dispositivo que no puede hacerlo simplemente no muestra número.'),
('es','help_songs','El repertorio con tonalidad, tempo, duración y estado. Partituras, letras y grabaciones cuelgan de la canción. Para el escenario hay una vista a pantalla completa: texto grande, secciones destacadas en color y desplazamiento automático — el ritmo se ajusta con el botón de tempo, como número o marcando el compás. La pantalla se mantiene encendida. Quien prefiera leer su propia hoja de acordes cambia a ella arriba.'),
('es','help_orte','Lugares con dirección, persona de contacto y lo que pasó las veces anteriores. Con "Buscar dirección" el servidor obtiene una vez las coordenadas de OpenStreetMap y rellena de paso dirección y localidad — tiene que estar permitido en Ajustes → Conexiones hacia fuera, si no el botón se queda gris. El icono de navegación abre la aplicación de mapas de tu dispositivo con el destino; en el iPhone eliges cuál la primera vez.'),
('es','help_fotos','Imágenes para la página pública y para el archivo. Al subirlas, la aplicación lee del archivo la fecha y el lugar de captura y con ellos propone a qué fecha pertenece una foto — la asignación solo ocurre al hacer clic. Después esos datos se eliminan del archivo guardado: un local de ensayo suele ser un domicilio, y eso no debe salir con una foto publicada. Solo los originales directos del dispositivo los llevan; lo que se ha compartido por mensajería los perdió hace tiempo.'),
('it','app_install_offline','Senza rete — la norma sui palchi — c''è comunque tutto: panoramica, date, scalette con la versione da stampare, brani con testi, accordi e allegati, il rider e la lista canali. Funziona così di serie, perché nessuno scopra sul palco di non aver portato niente. Se vuoi meno — accordi e allegati occupano spazio — togli la spunta nel profilo alla voce "portare offline". Alla disconnessione viene cancellato tutto, così su un telefono condiviso nessuno trova le date del precedente.'),
('it','app_install_push','Le notifiche sul dispositivo si trovano nel profilo. Tutti e tre i temi sono preselezionati — nuove date, nuovi commenti, conferme e disdette — quindi togli la spunta più che metterla. Non parte nulla finché non registri il dispositivo lì; il browser chiede da sé il permesso. Su iPhone funziona solo con l''app installata. Se la sezione non compare nel profilo, l''amministrazione della band ha disattivato le notifiche oppure al server mancano i requisiti.'),
('it','app_install_badge','Sull''icona compare un numero quando qualcosa ti aspetta: i tuoi compiti aperti e le date in arrivo a cui non hai ancora risposto. Si aggiungono le notifiche arrivate mentre l''app era chiusa. Aprendo l''app le notifiche spariscono dal numero — i compiti restano, perché un compito non si conclude guardandolo. Su iPhone il numero lo scrive l''app stessa; su Android il sistema lo ricava dalle notifiche nella barra, e se lì compaia un numero o solo un puntino lo decide la schermata Home. Un dispositivo che non può farlo semplicemente non mostra il numero.'),
('it','help_songs','Il repertorio con tonalità, tempo, durata e stato. Spartiti, testi e registrazioni sono agganciati al brano. Per il palco c''è una vista a schermo intero: testo grande, sezioni evidenziate a colori e scorrimento automatico — il ritmo si imposta con il pulsante del tempo, come numero o battendo la misura. Lo schermo resta acceso. Chi preferisce leggere il proprio foglietto di accordi ci passa dall''alto.'),
('it','help_orte','I luoghi con indirizzo, referente ed esperienze delle volte precedenti. Con "Cerca indirizzo" il server recupera una volta le coordinate da OpenStreetMap e compila subito indirizzo e città — deve essere consentito in Impostazioni → Connessioni verso l''esterno, altrimenti il pulsante resta grigio. Il simbolo di navigazione apre l''app di mappe del dispositivo con la destinazione; su iPhone la prima volta scegli quale.'),
('it','help_fotos','Immagini per la pagina pubblica e per l''archivio. Al caricamento l''applicazione legge dal file la data e il luogo dello scatto e con questi propone a quale data appartenga una foto — l''abbinamento avviene solo con un clic. Quelle informazioni vengono poi rimosse dal file conservato: una sala prove è spesso un''abitazione privata, e non deve uscire insieme a una foto pubblicata. Solo gli originali presi direttamente dal dispositivo le contengono; ciò che è stato condiviso via messenger le ha perse da tempo.');
