-- Die Hilfe inhaltlich nachgezogen (#370).
--
-- Die Kette „Anfrage → Angebot → Vertrag → Rechnung → Kasse" endete in der
-- Erklärung bei der Kasse: Die Rechnung kam gar nicht vor, obwohl sie seit
-- zwei Auslieferungen dazwischensteht. Dazu zwei fehlende Aufgaben, ein
-- fehlender Eintrag in der Markenliste und ein Hinweis, wo das Rechenblatt im
-- einstufigen Weg zu finden ist.
--
-- DELETE für die geänderten Texte, weil die INSERTs mit
-- ON DUPLICATE KEY UPDATE value = value laufen und sonst der alte Stand
-- stehen bliebe.
SET NAMES utf8mb4;

DELETE FROM translations WHERE tkey IN
  ('help_flow_gig', 'help_flow_direct', 'help_flow_setlist', 'help_flow_money', 'help_termine_3');

INSERT INTO translations (lang, tkey, value) VALUES
('en','help_flow_gig','From the enquiry to the money: somebody asks, you create an event. From the event you calculate a quote — it takes the date and the playing time from there. If the promoter says yes, the quote becomes a contract and the fee travels with it, so that two figures never sit side by side. The event then shows whether the signed sheet has come back. If the promoter is to get an invoice, tick "create invoice" on the event — it is built from the contract, with promoter, date and amount. After the gig you take the fee into the cash book, and at the end of the year it appears in the tax overview.'),
('en','help_flow_direct','From the enquiry to the money: somebody asks, you create an event and send the contract with it. Date, playing time and fee come from the event, so you copy nothing. If somebody asks the price first, work it out on the event with "calculate price" from your rate list; the total travels into the contract as the fee. When the contract comes back signed you note that, and from then on the event shows that the paper is in. If the promoter is to get an invoice, tick "create invoice" on the event — it is built from the contract. After the gig you take the fee into the cash book, and at the end of the year it appears in the tax overview. If you want to send the calculation out as a quote of its own before the contract, switch to the two-step route in the settings.'),
('en','help_flow_setlist','What happens on stage: you collect songs once, and a setlist is a selection of them in order. You attach the setlist to the event. The stage rider describes the technical requirements and applies to every gig alike — it does not hang on the single event. In print, setlist, rider, quote, contract and invoice look the same, because they share the same head with the logo and the watermark.'),
('en','help_flow_money','Money comes together in three places. The cash book holds income and expenditure; buying a piece of equipment does not count as expenditure there but appears as an acquisition in the tax overview and spreads across the years. The fee for a gig comes from the event — what you charged the promoter for it sits next to it under invoices. The small-business turnover threshold is calculated from everything that came in.'),
('en','help_termine_3','What is new or has changed carries a mark: "new", or "changed" with the name and the day. Your own changes never mark, and somebody joining does not find the whole band history unread. What gets marked is what concerns the band: date, times, place, fee, status, setlist, notes — an invoice number added afterwards makes no mark. Marks exist in nearly every area: events, comments, replies, songs, setlists, quotes, contracts, files, places, absences, tasks, cash book, invoices, equipment, guests, photos, mailbox, music &amp; videos, stage rider and channels. Where an entry unfolds — an event, a piece of equipment — the mark disappears on unfolding. Where it stands complete in the list, it counts as seen once the list is opened and the mark is gone next time. Two exceptions: members carry no marks, and the chat counts unread posts its own way.'),
('en','help_angebote_5','Where you find the sheet depends on the route you chose. If it goes out as a quote, "quotes" is in the menu. If it stays in the house, the "calculate price" button on the event leads to it — the same sheet, only without a menu entry of its own, because then nobody outside the band sees it.'),
('en','help_task_contract','draw up a contract and send it'),
('en','help_task_invoice','write the promoter an invoice'),

('nl','help_flow_gig','Van de aanvraag tot het geld: iemand vraagt, jullie maken een agendapunt aan. Daaruit rekenen jullie een offerte — datum en speeltijd haalt die daarvandaan. Zegt de organisator ja, dan wordt de offerte een contract en de gage gaat mee, zodat er nooit twee bedragen naast elkaar staan. Bij het agendapunt staat daarna of het getekende blad terug is. Moet de organisator een factuur krijgen, dan zet je bij het agendapunt het vinkje "factuur aanmaken" — die ontstaat uit het contract, met organisator, datum en bedrag. Na het optreden boeken jullie de gage in de kas, en aan het eind van het jaar staat die in het belastingoverzicht.'),
('nl','help_flow_direct','Van de aanvraag tot het geld: iemand vraagt, jullie maken een agendapunt aan en sturen het contract erbij. Datum, speeltijd en gage komen van het agendapunt, overschrijven hoeft niet. Vraagt iemand vooraf naar de prijs, dan reken je die bij het agendapunt met "prijs berekenen" uit jullie tarieven uit; het totaal gaat als gage het contract in. Komt het contract getekend terug, dan noteren jullie dat, en vanaf dan staat bij het agendapunt dat het papier binnen is. Moet de organisator een factuur krijgen, dan zet je het vinkje "factuur aanmaken" — die ontstaat uit het contract. Na het optreden boeken jullie de gage in de kas, en aan het eind van het jaar staat die in het belastingoverzicht. Willen jullie de berekening als eigen offerte versturen vóór het contract, zet dan in de instellingen de tweetrapsweg aan.'),
('nl','help_flow_setlist','Wat er op het podium gebeurt: nummers verzamelen jullie één keer, en een setlist is een selectie daaruit op volgorde. De setlist hang je aan het agendapunt. De stagerider beschrijft wat jullie aan techniek nodig hebben en geldt voor elk optreden gelijk — hij hangt niet aan het losse agendapunt. Afgedrukt zien setlist, rider, offerte, contract en factuur er hetzelfde uit, omdat ze dezelfde kop met logo en watermerk delen.'),
('nl','help_flow_money','Geld komt op drie plaatsen samen. In de kas staan inkomsten en uitgaven; de aankoop van apparatuur telt daar niet als uitgave maar verschijnt als aanschaf in het belastingoverzicht en verdeelt zich over de jaren. De gage van een optreden komt uit het agendapunt — wat jullie de organisator daarvoor in rekening brachten staat ernaast bij de facturen. De omzetgrens van de kleineondernemersregeling wordt berekend uit alles wat binnenkwam.'),
('nl','help_termine_3','Wat nieuw is of gewijzigd draagt een merkteken: "nieuw", of "gewijzigd" met de naam en de dag. Eigen wijzigingen geven nooit een teken, en wie er nieuw bij komt vindt niet de hele bandgeschiedenis als ongelezen. Gemarkeerd wordt wat de band aangaat: datum, tijden, plaats, gage, status, setlist, notities — een later toegevoegd factuurnummer geeft geen teken. Merktekens zijn er in bijna elk onderdeel: agenda, reacties, toe- en afzeggingen, nummers, setlists, offertes, contracten, bestanden, locaties, afwezigheden, taken, kas, facturen, apparatuur, gasten, foto''s, postvak, muziek &amp; video''s, stagerider en kanalen. Waar een regel uitklapt — agendapunt, apparaat — verdwijnt het teken bij het uitklappen. Waar hij volledig in de lijst staat, geldt hij als gezien zodra de lijst is geopend. Twee uitzonderingen: bij leden zijn er geen tekens, en de chat telt ongelezen berichten op zijn eigen manier.'),
('nl','help_angebote_5','Waar je het blad vindt hangt af van de gekozen weg. Gaat het als offerte naar buiten, dan staat "offertes" in het menu. Blijft het binnenshuis, dan leidt de knop "prijs berekenen" bij het agendapunt ernaartoe — hetzelfde blad, alleen zonder eigen menu-item, omdat niemand buiten de band het dan te zien krijgt.'),
('nl','help_task_contract','een contract opstellen en versturen'),
('nl','help_task_invoice','de organisator een factuur schrijven'),

('fr','help_flow_gig','De la demande à l''argent : quelqu''un demande, vous créez une date. À partir de la date vous calculez un devis — il y prend le jour et la durée de jeu. Si l''organisateur accepte, le devis devient un contrat et le cachet suit, pour que deux chiffres ne vivent jamais côte à côte. La date indique ensuite si la feuille signée est revenue. Si l''organisateur doit recevoir une facture, cochez « créer la facture » sur la date — elle naît du contrat, avec l''organisateur, la date et le montant. Après le concert vous passez le cachet en caisse, et en fin d''année il figure au récapitulatif fiscal.'),
('fr','help_flow_direct','De la demande à l''argent : quelqu''un demande, vous créez une date et envoyez le contrat avec. Jour, horaire et cachet viennent de la date, rien à recopier. Si l''on vous demande le prix avant, calculez-le sur la date avec « calculer le prix » à partir de vos tarifs ; le total passe au contrat comme cachet. Quand le contrat revient signé vous le notez, et la date indique dès lors que le papier est là. Si l''organisateur doit recevoir une facture, cochez « créer la facture » sur la date — elle naît du contrat. Après le concert vous passez le cachet en caisse, et en fin d''année il figure au récapitulatif fiscal. Si vous voulez envoyer le calcul comme devis à part avant le contrat, passez au parcours en deux temps dans les réglages.'),
('fr','help_flow_setlist','Ce qui se passe sur scène : vous rassemblez les morceaux une fois, et une setlist en est une sélection dans l''ordre. La setlist s''accroche à la date. La fiche technique décrit ce qu''il vous faut et vaut pour tous les concerts — elle ne tient pas à une date en particulier. À l''impression, setlist, fiche technique, devis, contrat et facture se ressemblent, parce qu''ils partagent le même en-tête avec le logo et le filigrane.'),
('fr','help_flow_money','L''argent se rejoint en trois endroits. La caisse tient les recettes et les dépenses ; l''achat de matériel n''y compte pas comme dépense mais apparaît comme acquisition au récapitulatif fiscal et s''étale sur les années. Le cachet d''un concert vient de la date — ce que vous avez facturé à l''organisateur pour lui se trouve à côté, dans les factures. Le seuil de chiffre d''affaires de la franchise se calcule sur tout ce qui est entré.'),
('fr','help_termine_3','Ce qui est nouveau ou modifié porte une marque : « nouveau », ou « modifié » avec le nom et le jour. Vos propres modifications ne marquent jamais, et celui qui arrive ne trouve pas toute l''histoire du groupe comme non lue. Est marqué ce qui concerne le groupe : date, horaires, lieu, cachet, état, setlist, notes — un numéro de facture ajouté après coup ne marque pas. Il y a des marques dans presque tous les domaines : dates, commentaires, réponses, morceaux, setlists, devis, contrats, fichiers, lieux, absences, tâches, caisse, factures, matériel, invités, photos, boîte aux lettres, musique et vidéos, fiche technique et canaux. Là où une ligne se déplie — une date, un appareil — la marque disparaît au dépliage. Là où elle figure entière dans la liste, elle compte pour vue dès l''ouverture de la liste. Deux exceptions : les membres ne portent pas de marques, et le fil de discussion compte les messages non lus à sa façon.'),
('fr','help_angebote_5','Où trouver la feuille dépend du parcours choisi. Si elle part comme devis, « devis » figure au menu. Si elle reste à la maison, le bouton « calculer le prix » sur la date y mène — la même feuille, simplement sans entrée de menu, puisque personne d''autre que vous ne la voit alors.'),
('fr','help_task_contract','rédiger un contrat et l''envoyer'),
('fr','help_task_invoice','écrire une facture à l''organisateur'),

('es','help_flow_gig','De la consulta al dinero: alguien pregunta y vosotros creáis una fecha. A partir de la fecha calculáis un presupuesto — de ahí toma el día y la duración. Si el organizador acepta, el presupuesto se convierte en contrato y el caché viaja con él, para que nunca convivan dos cifras. La fecha muestra después si la hoja firmada ha vuelto. Si el organizador debe recibir una factura, marcad en la fecha «crear factura» — nace del contrato, con organizador, fecha e importe. Tras la actuación pasáis el caché a la caja, y a fin de año aparece en el resumen fiscal.'),
('es','help_flow_direct','De la consulta al dinero: alguien pregunta, creáis una fecha y enviáis el contrato con ella. Día, horario y caché vienen de la fecha, no hay que copiar nada. Si alguien pregunta antes el precio, lo calculáis en la fecha con «calcular precio» a partir de vuestra lista de tarifas; el total pasa al contrato como caché. Cuando el contrato vuelve firmado lo anotáis, y desde entonces la fecha muestra que el papel está. Si el organizador debe recibir una factura, marcad «crear factura» — nace del contrato. Tras la actuación pasáis el caché a la caja, y a fin de año aparece en el resumen fiscal. Si queréis enviar el cálculo como presupuesto propio antes del contrato, cambiad en los ajustes a la vía en dos pasos.'),
('es','help_flow_setlist','Lo que pasa en el escenario: las canciones se reúnen una vez, y un repertorio es una selección de ellas en orden. El repertorio se cuelga de la fecha. El rider describe lo que necesitáis de técnica y vale igual para todas las actuaciones — no depende de la fecha concreta. Impresos, repertorio, rider, presupuesto, contrato y factura se ven iguales, porque comparten la misma cabecera con logotipo y marca de agua.'),
('es','help_flow_money','El dinero confluye en tres sitios. En la caja están los ingresos y los gastos; la compra de un equipo no cuenta ahí como gasto, sino que aparece como adquisición en el resumen fiscal y se reparte entre los años. El caché de una actuación viene de la fecha — lo que le facturasteis al organizador por ella está al lado, en las facturas. El límite de facturación del régimen de pequeña empresa se calcula con todo lo que entró.'),
('es','help_termine_3','Lo nuevo o lo cambiado lleva una marca: «nuevo», o «cambiado» con el nombre y el día. Los cambios propios nunca marcan, y quien se incorpora no encuentra toda la historia del grupo sin leer. Se marca lo que atañe al grupo: fecha, horas, lugar, caché, estado, repertorio, notas — un número de factura añadido después no marca. Hay marcas en casi todas las áreas: fechas, comentarios, confirmaciones, canciones, repertorios, presupuestos, contratos, archivos, lugares, ausencias, tareas, caja, facturas, equipo, invitados, fotos, buzón, música y vídeos, rider y canales. Donde una entrada se despliega — una fecha, un aparato — la marca desaparece al desplegarla. Donde figura entera en la lista, cuenta como vista al abrir la lista. Dos excepciones: los miembros no llevan marcas, y el chat cuenta los mensajes sin leer a su manera.'),
('es','help_angebote_5','Dónde encontráis la hoja depende de la vía elegida. Si sale como presupuesto, «presupuestos» está en el menú. Si se queda en casa, el botón «calcular precio» de la fecha lleva a ella — la misma hoja, solo que sin entrada propia en el menú, porque entonces no la ve nadie fuera del grupo.'),
('es','help_task_contract','redactar un contrato y enviarlo'),
('es','help_task_invoice','escribirle una factura al organizador'),

('it','help_flow_gig','Dalla richiesta al denaro: qualcuno chiede, voi create una data. Dalla data calcolate un preventivo — giorno e durata li prende da lì. Se l''organizzatore accetta, il preventivo diventa un contratto e il compenso lo segue, così due cifre non convivono mai. La data mostra poi se il foglio firmato è tornato. Se l''organizzatore deve ricevere una fattura, spuntate sulla data «crea fattura» — nasce dal contratto, con organizzatore, data e importo. Dopo il concerto portate il compenso in cassa, e a fine anno compare nel riepilogo fiscale.'),
('it','help_flow_direct','Dalla richiesta al denaro: qualcuno chiede, voi create una data e inviate il contratto. Giorno, orario e compenso vengono dalla data, non c''è niente da ricopiare. Se qualcuno chiede prima il prezzo, lo calcolate sulla data con «calcola prezzo» dal vostro listino; il totale entra nel contratto come compenso. Quando il contratto torna firmato lo annotate, e da allora la data mostra che il foglio c''è. Se l''organizzatore deve ricevere una fattura, spuntate «crea fattura» — nasce dal contratto. Dopo il concerto portate il compenso in cassa, e a fine anno compare nel riepilogo fiscale. Se volete inviare il calcolo come preventivo a sé stante prima del contratto, passate nelle impostazioni al percorso in due passi.'),
('it','help_flow_setlist','Quello che succede sul palco: i brani si raccolgono una volta, e una scaletta è una selezione di quelli in ordine. La scaletta si aggancia alla data. La scheda tecnica descrive ciò che vi serve e vale uguale per ogni concerto — non dipende dalla singola data. Stampati, scaletta, scheda tecnica, preventivo, contratto e fattura si somigliano, perché condividono la stessa testata con logo e filigrana.'),
('it','help_flow_money','Il denaro confluisce in tre punti. In cassa stanno entrate e uscite; l''acquisto di un''attrezzatura lì non conta come uscita, ma compare come acquisto nel riepilogo fiscale e si distribuisce sugli anni. Il compenso di un concerto viene dalla data — quello che avete fatturato all''organizzatore sta accanto, tra le fatture. La soglia di ricavi del regime agevolato si calcola su tutto ciò che è entrato.'),
('it','help_termine_3','Ciò che è nuovo o è cambiato porta un contrassegno: «nuovo», oppure «modificato» con il nome e il giorno. Le proprie modifiche non contrassegnano mai, e chi arriva non trova tutta la storia della band come non letta. Viene contrassegnato ciò che riguarda la band: data, orari, luogo, compenso, stato, scaletta, note — un numero di fattura aggiunto dopo non contrassegna. I contrassegni ci sono in quasi ogni area: date, commenti, conferme, brani, scalette, preventivi, contratti, file, luoghi, assenze, compiti, cassa, fatture, attrezzatura, ospiti, foto, posta, musica e video, scheda tecnica e canali. Dove una voce si apre — una data, un apparecchio — il contrassegno sparisce all''apertura. Dove sta per intero nell''elenco, vale come vista appena l''elenco è aperto. Due eccezioni: i membri non portano contrassegni, e la chat conta i messaggi non letti a modo suo.'),
('it','help_angebote_5','Dove trovate il foglio dipende dal percorso scelto. Se esce come preventivo, «preventivi» sta nel menu. Se resta in casa, il pulsante «calcola prezzo» sulla data ci porta — lo stesso foglio, solo senza una voce di menu propria, perché allora non lo vede nessuno fuori dalla band.'),
('it','help_task_contract','redigere un contratto e inviarlo'),
('it','help_task_invoice','scrivere una fattura all''organizzatore')
ON DUPLICATE KEY UPDATE value = value;
