-- Legal form and liability. Applies whether or not the band uses the small
-- business rule, so it sits in the tax overview section, not in that one.
SET NAMES utf8mb4;

INSERT INTO translations (lang, tkey, value) VALUES
('en','help_gbr_title','Legal form and liability'),
('en','help_gbr_form','As soon as several people perform together, share a fee and buy gear jointly, they are a partnership under civil law. That needs no contract, no registration and no name — it comes about through the doing (§ 705 BGB). It is different only without a common purpose: where one person is the band and pays musicians per gig, or where everybody invoices separately. Then there is a bandleader and self-employed players, each with their own figures.'),
('en','help_gbr_liability','Something follows from that which is worth knowing: in such a partnership every member is liable personally, jointly and severally, and without limit — with private assets, not merely with what sits in the band account (§ 721 BGB). Whoever is owed money may choose which of you to pursue. An agreement among yourselves changes nothing about that: it works between you, not towards the landlord or the promoter. And anybody joining later is liable for what arose before (§ 721a BGB) — a thing to discuss before somebody joins, not after.'),
('en','help_gbr_register','Since 1 January 2024 there is a company register and the registered eGbR. Entry is voluntary and needed neither for the partnership to exist nor for its legal capacity; it is required only where the partnership itself is to appear in another register, the land register for instance. For a band that plays gigs and rents a rehearsal room it is as a rule dispensable. Registration changes nothing about the personal liability in any case.'),
('en','help_tax_band','The turnover of the band as a whole is what counts, not per head. For VAT the partnership is the taxable person, so the limit applies once for everybody together. Where each member invoices separately, each has their own limit, and the figure in the books says nothing about it.'),
('fr','help_gbr_title','Forme juridique et responsabilité'),
('fr','help_gbr_form','Dès que plusieurs personnes se produisent ensemble, partagent un cachet et achètent du matériel en commun, elles forment une société de droit civil. Cela ne demande ni contrat, ni immatriculation, ni nom — elle naît du fait même (§ 705 BGB). Il en va autrement seulement en l''absence de but commun : lorsqu''une personne est le groupe et paie des musiciens au concert, ou que chacun facture séparément. Il y a alors un chef d''orchestre et des indépendants, chacun avec ses propres chiffres.'),
('fr','help_gbr_liability','Il en découle une chose qu''il faut connaître : dans une telle société, chaque membre répond personnellement, solidairement et sans limite — sur son patrimoine privé, et pas seulement sur ce qui se trouve dans la caisse du groupe (§ 721 BGB). Le créancier choisit lequel d''entre vous il poursuit. Un accord entre vous n''y change rien : il vaut entre vous, pas envers la bailleresse ou l''organisateur. Et celui qui arrive plus tard répond aussi de ce qui est né avant (§ 721a BGB) — cela se discute avant l''entrée, pas après.'),
('fr','help_gbr_register','Depuis le 1er janvier 2024 existent un registre des sociétés et l''eGbR immatriculée. L''immatriculation est facultative et n''est nécessaire ni à l''existence de la société ni à sa capacité juridique ; elle n''est exigée que si la société doit elle-même figurer dans un autre registre, le livre foncier par exemple. Pour un groupe qui joue des concerts et loue un local de répétition, elle est en règle générale superflue. Une immatriculation ne change de toute façon rien à la responsabilité personnelle.'),
('fr','help_tax_band','C''est le chiffre d''affaires du groupe dans son ensemble qui compte, non par tête. Pour la TVA, la société est l''assujetti : le seuil vaut donc une seule fois pour tous. Si en revanche chaque membre établit ses propres factures, chacun a son propre seuil, et le chiffre de la caisse n''en dit rien.'),
('es','help_gbr_title','Forma jurídica y responsabilidad'),
('es','help_gbr_form','En cuanto varias personas actúan juntas, reparten un caché y compran equipo en común, forman una sociedad civil. No hace falta contrato, ni inscripción, ni nombre — surge por el hecho mismo (§ 705 BGB). Solo es distinto sin un fin común: cuando una persona es la banda y paga músicos por actuación, o cuando cada uno factura por separado. Entonces hay un líder de banda y autónomos, cada uno con sus propias cifras.'),
('es','help_gbr_liability','De ahí se sigue algo que conviene saber: en una sociedad así cada miembro responde personal, solidaria e ilimitadamente — con su patrimonio privado, no solo con lo que hay en la caja de la banda (§ 721 BGB). Quien tenga un crédito puede elegir a cuál de vosotros reclama. Un acuerdo entre vosotros no cambia nada: rige entre vosotros, no frente a la arrendadora o al promotor. Y quien entra después responde también de lo surgido antes (§ 721a BGB) — eso se habla antes de la incorporación, no después.'),
('es','help_gbr_register','Desde el 1 de enero de 2024 existen un registro de sociedades y la eGbR inscrita. La inscripción es voluntaria y no es necesaria ni para la existencia de la sociedad ni para su capacidad jurídica; solo se exige cuando la propia sociedad deba figurar en otro registro, por ejemplo el registro de la propiedad. Para una banda que da conciertos y alquila un local de ensayo suele ser prescindible. La inscripción, en todo caso, no altera la responsabilidad personal.'),
('es','help_tax_band','Cuenta el volumen de negocio de la banda en conjunto, no por cabeza. A efectos del IVA la sociedad es el sujeto pasivo, de modo que el límite rige una sola vez para todos. Si en cambio cada miembro emite sus propias facturas, cada uno tiene su propio límite, y la cifra de la caja no dice nada al respecto.'),
('nl','help_gbr_title','Rechtsvorm en aansprakelijkheid'),
('nl','help_gbr_form','Zodra meerdere mensen samen optreden, een gage delen en samen apparatuur aanschaffen, vormen zij een maatschap naar burgerlijk recht. Daarvoor is geen contract nodig, geen inschrijving en geen naam — zij ontstaat door het doen (§ 705 BGB). Anders ligt het alleen zonder gemeenschappelijk doel: wanneer één persoon de band is en muzikanten per optreden betaalt, of wanneer ieder zelf factureert. Dan is er een bandleider en zijn er zelfstandigen, elk met eigen cijfers.'),
('nl','help_gbr_liability','Daaruit volgt iets wat je moet weten: in zo''n maatschap is elk lid persoonlijk, hoofdelijk en onbeperkt aansprakelijk — met het privévermogen, niet alleen met wat er in de bandkas zit (§ 721 BGB). Wie geld tegoed heeft, mag kiezen wie van jullie hij aanspreekt. Een afspraak onderling verandert daar niets aan: die werkt tussen jullie, niet tegenover de verhuurder of de organisator. En wie later toetreedt, is ook aansprakelijk voor wat eerder is ontstaan (§ 721a BGB) — dat bespreek je vóór de toetreding, niet erna.'),
('nl','help_gbr_register','Sinds 1 januari 2024 bestaan er een vennootschapsregister en de ingeschreven eGbR. Inschrijving is vrijwillig en nodig noch voor het bestaan van de vennootschap noch voor haar rechtsbevoegdheid; zij wordt pas verlangd wanneer de vennootschap zelf in een ander register moet, bijvoorbeeld het kadaster. Voor een band die optredens speelt en een oefenruimte huurt is zij doorgaans overbodig. Aan de persoonlijke aansprakelijkheid verandert een inschrijving hoe dan ook niets.'),
('nl','help_tax_band','Geteld wordt de omzet van de band als geheel, niet per hoofd. Voor de btw is de vennootschap de belastingplichtige, dus geldt de grens één keer voor iedereen samen. Factureert daarentegen elk lid zelf, dan heeft ieder zijn eigen grens, en het getal in de kas zegt daar niets over.'),
('it','help_gbr_title','Forma giuridica e responsabilità'),
('it','help_gbr_form','Non appena più persone si esibiscono insieme, dividono un cachet e acquistano attrezzatura in comune, costituiscono una società di diritto civile. Non servono né contratto, né iscrizione, né nome — nasce dal fatto stesso (§ 705 BGB). È diverso soltanto in assenza di uno scopo comune: quando una persona è la band e paga i musicisti a serata, oppure quando ciascuno fattura per conto proprio. Allora ci sono un bandleader e dei lavoratori autonomi, ognuno con i propri numeri.'),
('it','help_gbr_liability','Ne discende qualcosa che conviene sapere: in una società simile ogni membro risponde personalmente, in solido e senza limiti — con il patrimonio privato, non solo con quanto si trova nella cassa della band (§ 721 BGB). Chi vanta un credito può scegliere chi di voi chiamare in causa. Un accordo tra voi non cambia nulla: vale tra voi, non verso la locatrice o l''organizzatore. E chi entra dopo risponde anche di ciò che è sorto prima (§ 721a BGB) — se ne parla prima dell''ingresso, non dopo.'),
('it','help_gbr_register','Dal 1° gennaio 2024 esistono un registro delle società e la eGbR iscritta. L''iscrizione è volontaria e non è necessaria né per l''esistenza della società né per la sua capacità giuridica; è richiesta solo quando la società stessa debba figurare in un altro registro, per esempio quello immobiliare. Per una band che suona concerti e affitta una sala prove è di regola superflua. All''iscrizione, in ogni caso, non consegue alcun cambiamento della responsabilità personale.'),
('it','help_tax_band','Si conta il volume d''affari della band nel suo insieme, non pro capite. Ai fini IVA il soggetto passivo è la società, quindi la soglia vale una sola volta per tutti insieme. Se invece ogni membro emette fatture proprie, ciascuno ha la propria soglia, e il numero in cassa non dice nulla al riguardo.')
ON DUPLICATE KEY UPDATE value = value;
