-- Who shares in the profit. Not every account belongs to a partner, and one
-- that does not would silently take a share from everybody else.
SET NAMES utf8mb4;

INSERT INTO translations (lang, tkey, value) VALUES
('en','mem_profit_share','Shares in the profit'),
('en','mem_profit_share_hint','Partners share the profit and each declares their part. Anybody working for the band without being a partner — management, sound, an account left over from earlier times — belongs unticked here: otherwise they take a share and everybody else is short of it.'),
('en','taxr_share_hint','Shown are the people who share in the profit; anybody unticked under members does not appear here. The share is worked out in equal parts — that is what applies to a partnership without a differing agreement. If you agreed on another split, this column is wrong; the books do not know your agreement. Where "cash net" falls well behind for individual members, they carry more than the others: the deduction for rent and rehearsal room lowers the profit for everybody, no matter who paid it. That is not straightened out through tax but in the books — by repaying the deposits before the profit is distributed. It changes no tax figure, because repaying capital is as little income as contributing it was an expense.'),
('fr','mem_profit_share','Participe au bénéfice'),
('fr','mem_profit_share_hint','Les associés se partagent le bénéfice et chacun déclare sa part. Qui travaille pour le groupe sans être associé — management, technique, un compte hérité d''une autre époque — doit être décoché ici : sinon il prend une part, et elle manque à tous les autres.'),
('fr','taxr_share_hint','Sont affichées les personnes qui participent au bénéfice ; celles décochées parmi les membres n''y figurent pas. La part est calculée à parts égales — c''est ce qui s''applique à une société de personnes sans convention contraire. Si vous avez convenu d''une autre répartition, cette colonne est fausse ; la caisse ne connaît pas votre accord. Lorsque la « trésorerie nette » décroche nettement pour certains, ceux-là portent plus que les autres : la déduction du loyer et du local de répétition abaisse le bénéfice pour tout le monde, quel qu''en soit le payeur. Cela ne se corrige pas par l''impôt mais dans la caisse — en remboursant les apports avant de distribuer le bénéfice. Aucun montant fiscal n''en est modifié, car rembourser un apport est aussi peu un revenu que l''apport était une dépense.'),
('es','mem_profit_share','Participa en el beneficio'),
('es','mem_profit_share_hint','Los socios se reparten el beneficio y cada uno declara su parte. Quien trabaja para la banda sin ser socio — gestión, técnica, una cuenta que quedó de otros tiempos — debe quedar desmarcado aquí: de lo contrario se lleva una parte y a todos los demás les falta.'),
('es','taxr_share_hint','Se muestran las personas que participan en el beneficio; quien esté desmarcado entre los miembros no aparece aquí. La participación se calcula a partes iguales — así rige en una sociedad de personas sin acuerdo distinto. Si habéis pactado otro reparto, esta columna no es correcta; la caja no conoce vuestro acuerdo. Cuando la «caja neta» queda claramente por debajo en algunos, esos cargan más que el resto: la deducción del alquiler y del local de ensayo reduce el beneficio para todos, con independencia de quién lo pagó. Eso no se corrige por la vía fiscal, sino en la caja — devolviendo las aportaciones antes de repartir el beneficio. No cambia ninguna cifra fiscal, porque devolver capital es tan poco un ingreso como la aportación fue un gasto.'),
('nl','mem_profit_share','Deelt in de winst'),
('nl','mem_profit_share_hint','Vennoten delen de winst en geven ieder hun deel aan. Wie voor de band werkt zonder vennoot te zijn — management, techniek, een account uit vroeger tijden — hoort hier uitgevinkt: anders krijgt die een aandeel, en komt het bij alle anderen tekort.'),
('nl','taxr_share_hint','Getoond worden de mensen die in de winst delen; wie bij de leden is uitgevinkt, staat hier niet. Het aandeel is in gelijke delen berekend — zo geldt het bij een personenvennootschap zonder afwijkende afspraak. Hebben jullie een andere verdeling afgesproken, dan klopt deze kolom niet; de kas kent jullie afspraak niet. Blijft „kas netto" bij sommigen duidelijk achter, dan dragen zij meer dan de anderen: de aftrek voor huur en oefenruimte verlaagt de winst voor iedereen, ongeacht wie hem betaalde. Dat wordt niet via de belasting rechtgetrokken maar in de kas — door de inleg terug te betalen voordat de winst wordt verdeeld. Aan geen enkel belastingbedrag verandert dat iets, want kapitaal terugbetalen is net zomin inkomen als de inleg een uitgave was.'),
('it','mem_profit_share','Partecipa all''utile'),
('it','mem_profit_share_hint','I soci si dividono l''utile e ciascuno dichiara la propria quota. Chi lavora per la band senza essere socio — management, tecnica, un account rimasto da altri tempi — va deselezionato qui: altrimenti prende una quota, e agli altri manca.'),
('it','taxr_share_hint','Sono mostrate le persone che partecipano all''utile; chi è deselezionato tra i membri non compare qui. La quota è calcolata in parti uguali — così vale per una società di persone senza accordo diverso. Se avete pattuito un''altra ripartizione, questa colonna non è corretta; la cassa non conosce il vostro accordo. Quando la «cassa netta» resta nettamente indietro per alcuni, quelli sostengono più degli altri: la deduzione per affitto e sala prove abbassa l''utile per tutti, indipendentemente da chi l''ha pagato. Non si rimedia per via fiscale ma in cassa — restituendo i conferimenti prima di distribuire l''utile. Non cambia alcun importo fiscale, perché restituire capitale è reddito tanto poco quanto il conferimento era una spesa.')
ON DUPLICATE KEY UPDATE value = value;
