-- The founding year: no previous year, so the smaller limit applies to the
-- running one — as a hard ceiling, not as an outlook on the next.
SET NAMES utf8mb4;

INSERT INTO translations (lang, tkey, value) VALUES
('en','set_tax_start','Founded on'),
('en','set_tax_start_hint','Only matters for the founding year: there is no previous year then, and the smaller limit applies to the running one — as a hard ceiling. Nothing is projected to a full year, so starting in October means the same limit as everybody else. Leave empty if the band has been going for a while.'),
('en','tax_first_year','Founding year: there is no previous year, so the smaller limit applies to this one — and immediately. Exceed it and the exemption ends with the turnover that breaks it, not on 1 January.'),
('en','help_tax_first_year','In the first year there is no previous year, and then the smaller limit applies to the running one — as hard a ceiling as the large one usually is: exceed it and the exemption ends with the turnover that breaks it. Nothing is projected pro rata; starting in October means the same limit as starting in January. For the books to notice, the founding date belongs in the settings — without it they calculate as for any settled band.'),
('fr','set_tax_start','Fondé le'),
('fr','set_tax_start_hint','N''a d''importance que pour l''année de création : il n''y a alors pas d''année précédente, et le seuil le plus bas s''applique à l''année en cours — comme plafond dur. Rien n''est ramené à l''année entière : commencer en octobre donne le même seuil qu''à tout le monde. Laisser vide si le groupe existe depuis plus longtemps.'),
('fr','tax_first_year','Année de création : il n''y a pas d''année précédente, le seuil le plus bas vaut donc pour cette année — et immédiatement. S''il est dépassé, l''exonération prend fin avec le chiffre d''affaires qui le franchit, et non au 1er janvier.'),
('fr','help_tax_first_year','La première année, il n''y a pas d''année précédente, et le seuil le plus bas s''applique alors à l''année en cours — plafond aussi dur que l''est d''ordinaire le grand : dépassé, l''exonération cesse avec le chiffre d''affaires qui le franchit. Rien n''est calculé au prorata ; commencer en octobre donne le même seuil qu''en janvier. Pour que la caisse le sache, la date de création se saisit dans les réglages — sans elle, elle calcule comme pour un groupe établi.'),
('es','set_tax_start','Fundada el'),
('es','set_tax_start_hint','Solo importa en el año de fundación: entonces no hay año anterior y el límite menor rige para el año en curso — como techo duro. No se prorratea nada: empezar en octubre supone el mismo límite que para los demás. Déjalo vacío si la banda existe desde hace más tiempo.'),
('es','tax_first_year','Año de fundación: no hay año anterior, así que el límite menor rige para este año — y de inmediato. Si se supera, la exención termina con el importe que lo rebasa, no el 1 de enero.'),
('es','help_tax_first_year','En el primer año no hay año anterior, y entonces el límite menor rige para el año en curso — un techo tan duro como suele serlo el grande: si se supera, la exención acaba con el importe que lo rebasa. No se prorratea nada; empezar en octubre supone el mismo límite que empezar en enero. Para que la caja lo tenga en cuenta, la fecha de fundación va en los ajustes — sin ella calcula como para cualquier banda asentada.'),
('nl','set_tax_start','Opgericht op'),
('nl','set_tax_start_hint','Alleen van belang voor het oprichtingsjaar: er is dan geen vorig jaar, en de kleinere grens geldt voor het lopende — als harde bovengrens. Er wordt niets omgerekend naar een heel jaar: in oktober beginnen betekent dezelfde grens als voor iedereen. Laat leeg als de band al langer bestaat.'),
('nl','tax_first_year','Oprichtingsjaar: er is geen vorig jaar, dus geldt de kleinere grens voor dit jaar — en meteen. Wordt hij overschreden, dan eindigt de vrijstelling met de omzet die hem breekt, niet op 1 januari.'),
('nl','help_tax_first_year','In het eerste jaar is er geen vorig jaar, en dan geldt de kleinere grens voor het lopende — even hard als de grote dat gewoonlijk is: overschreden eindigt de vrijstelling met de omzet die hem breekt. Er wordt niets naar rato omgerekend; in oktober beginnen geeft dezelfde grens als in januari. Wil de kas dat weten, dan hoort de oprichtingsdatum in de instellingen — zonder die rekent zij als voor elke gevestigde band.'),
('it','set_tax_start','Fondata il'),
('it','set_tax_start_hint','Conta solo per l''anno di fondazione: allora non c''è un anno precedente e la soglia più bassa vale per l''anno in corso — come tetto rigido. Non si ragguaglia nulla: iniziare a ottobre significa la stessa soglia che per tutti gli altri. Lascia vuoto se la band esiste da più tempo.'),
('it','tax_first_year','Anno di fondazione: non c''è un anno precedente, quindi la soglia più bassa vale per quest''anno — e subito. Se viene superata, l''esenzione finisce con l''operazione che la supera, non il 1° gennaio.'),
('it','help_tax_first_year','Nel primo anno non c''è un anno precedente, e allora la soglia più bassa vale per quello in corso — tetto rigido quanto lo è di solito quello grande: superata, l''esenzione finisce con l''operazione che la supera. Non si ragguaglia nulla; iniziare a ottobre dà la stessa soglia che iniziare a gennaio. Perché la cassa lo sappia, la data di fondazione va nelle impostazioni — senza di essa calcola come per qualsiasi band avviata.')
ON DUPLICATE KEY UPDATE value = value;
