-- A passkey belongs to a keychain, not to a device: one in iCloud covers
-- iPhone, iPad and Mac at once. Plus renaming an entry.
SET NAMES utf8mb4;

INSERT INTO translations (lang, tkey, value) VALUES
('en','prof_passkeys_hint','A passkey is a key that lives in your keychain and opens with face recognition, a fingerprint or the device lock. Neither face nor fingerprint leaves the device — what sits here is only the public half, with which nothing can be done but check whether a signature came from you. Your password stays alongside it and keeps working.'),
('en','prof_passkeys_sync','One per keychain is enough, not one per device: a passkey in the iCloud keychain counts on iPhone, iPad and Mac at once, one in a password manager everywhere that manager is set up. Only device-bound ones such as Windows Hello need their own per machine. A second one does no harm — it is simply a second way in.'),
('en','pk_rename','Rename'),
('en','fl_pk_renamed','Name changed.'),
('en','help_passkey_sync','How many you need depends on the keychain, not on how many devices you own. A passkey in the iCloud keychain syncs between iPhone, iPad and Mac — created once, usable everywhere. The same goes for a password manager: there it belongs to the account, not the device. Only device-bound methods such as Windows Hello need one per machine. Feel free to set up several anyway; they do not disturb each other, and if one is lost the others remain.'),
('fr','prof_passkeys_hint','Une clé d''accès est une clé qui réside dans votre trousseau et s''ouvre par reconnaissance faciale, empreinte digitale ou verrouillage de l''appareil. Ni le visage ni l''empreinte ne quittent l''appareil — ici ne se trouve que la moitié publique, avec laquelle on ne peut rien faire d''autre que vérifier qu''une signature vient bien de vous. Votre mot de passe reste à côté et continue de fonctionner.'),
('fr','prof_passkeys_sync','Une par trousseau suffit, pas une par appareil : une clé d''accès du trousseau iCloud vaut à la fois pour l''iPhone, l''iPad et le Mac ; une clé dans un gestionnaire de mots de passe vaut partout où celui-ci est installé. Seules les clés liées à un appareil, comme Windows Hello, en exigent une par machine. Une deuxième ne nuit pas — c''est simplement une deuxième porte.'),
('fr','pk_rename','Renommer'),
('fr','fl_pk_renamed','Nom modifié.'),
('fr','help_passkey_sync','Le nombre nécessaire dépend du trousseau, pas du nombre d''appareils. Une clé d''accès du trousseau iCloud se synchronise entre iPhone, iPad et Mac — créée une fois, utilisable partout. Il en va de même pour un gestionnaire de mots de passe : elle y appartient au compte, pas à l''appareil. Seules les méthodes liées à l''appareil, comme Windows Hello, en demandent une par machine. Vous pouvez malgré tout en créer plusieurs ; elles ne se gênent pas, et si l''une est perdue les autres demeurent.'),
('es','prof_passkeys_hint','Una clave de acceso es una clave que reside en tu llavero y se abre con reconocimiento facial, huella dactilar o el bloqueo del dispositivo. Ni el rostro ni la huella salen del dispositivo — aquí solo está la mitad pública, con la que no se puede hacer otra cosa que comprobar si una firma procede de ti. Tu contraseña se mantiene al lado y sigue funcionando.'),
('es','prof_passkeys_sync','Basta una por llavero, no una por dispositivo: una clave de acceso del llavero de iCloud vale a la vez para iPhone, iPad y Mac; una en un gestor de contraseñas vale allí donde ese gestor esté configurado. Solo las ligadas al dispositivo, como Windows Hello, necesitan una por equipo. Una segunda no molesta — es simplemente una segunda puerta.'),
('es','pk_rename','Renombrar'),
('es','fl_pk_renamed','Nombre cambiado.'),
('es','help_passkey_sync','Cuántas necesitas depende del llavero, no de cuántos dispositivos tengas. Una clave de acceso del llavero de iCloud se sincroniza entre iPhone, iPad y Mac — creada una vez, utilizable en todos. Lo mismo ocurre con un gestor de contraseñas: allí pertenece a la cuenta, no al dispositivo. Solo los métodos ligados al dispositivo, como Windows Hello, requieren una por equipo. Aun así puedes crear varias; no se estorban, y si se pierde una quedan las demás.'),
('nl','prof_passkeys_hint','Een passkey is een sleutel die in je sleutelbos ligt en opengaat met gezichtsherkenning, vingerafdruk of de schermvergrendeling. Gezicht noch vingerafdruk verlaat het apparaat — hier ligt alleen de openbare helft, waarmee niets anders kan dan controleren of een handtekening van jou komt. Je wachtwoord blijft ernaast bestaan en werkt gewoon door.'),
('nl','prof_passkeys_sync','Eén per sleutelbos volstaat, niet één per apparaat: een passkey in de iCloud-sleutelhanger geldt tegelijk op iPhone, iPad en Mac, een in een wachtwoordmanager overal waar die is ingesteld. Alleen apparaatgebonden varianten zoals Windows Hello hebben er per machine een nodig. Een tweede schaadt niet — dat is gewoon een tweede ingang.'),
('nl','pk_rename','Hernoemen'),
('nl','fl_pk_renamed','Naam gewijzigd.'),
('nl','help_passkey_sync','Hoeveel je er nodig hebt, hangt af van de sleutelbos, niet van het aantal apparaten. Een passkey in de iCloud-sleutelhanger synchroniseert tussen iPhone, iPad en Mac — eenmaal aangemaakt, overal bruikbaar. Hetzelfde geldt voor een wachtwoordmanager: daar hoort hij bij het account, niet bij het apparaat. Alleen apparaatgebonden methoden zoals Windows Hello vragen er per machine een. Maak er gerust toch meerdere aan; ze storen elkaar niet, en raakt er een kwijt, dan blijven de andere.'),
('it','prof_passkeys_hint','Una passkey è una chiave che risiede nel tuo portachiavi e si apre con riconoscimento del volto, impronta digitale o blocco del dispositivo. Né il volto né l''impronta lasciano il dispositivo — qui c''è solo la metà pubblica, con cui non si può fare altro che verificare se una firma proviene da te. La tua password resta accanto e continua a funzionare.'),
('it','prof_passkeys_sync','Ne basta una per portachiavi, non una per dispositivo: una passkey nel portachiavi iCloud vale insieme su iPhone, iPad e Mac; una in un gestore di password vale ovunque quel gestore sia configurato. Solo quelle legate al dispositivo, come Windows Hello, ne richiedono una per macchina. Una seconda non fa danno — è semplicemente una seconda porta.'),
('it','pk_rename','Rinomina'),
('it','fl_pk_renamed','Nome modificato.'),
('it','help_passkey_sync','Quante ne servono dipende dal portachiavi, non da quanti dispositivi hai. Una passkey nel portachiavi iCloud si sincronizza tra iPhone, iPad e Mac — creata una volta, utilizzabile ovunque. Lo stesso vale per un gestore di password: lì appartiene all''account, non al dispositivo. Solo i metodi legati al dispositivo, come Windows Hello, ne richiedono una per macchina. Puoi comunque crearne più di una; non si disturbano, e se una va persa restano le altre.'),
('en','help_passkey','Instead of a password you can sign in with a passkey: a key created inside the secured area of your device, which stays there. It opens the way you open your device — with your face, a fingerprint or a code. None of that reaches this server: it gets only the public half of the key and, at each sign-in, a signature over a random question that is valid exactly once. So there is no password here that could be stolen, and no sign-in that could be reused elsewhere. Set one up in your profile. In the list it appears under the name of its keychain — "Apple Passwords", "1Password", "Windows Hello" — because that is where it lives, and you can rename it at any time. Your password stays and keeps working: lose a device and you still get in with it, and remove the passkey in your profile.'),
('fr','help_passkey','Au lieu d''un mot de passe, vous pouvez vous connecter avec une clé d''accès : une clé créée dans la zone sécurisée de votre appareil, et qui y reste. Elle s''ouvre comme vous ouvrez votre appareil — visage, empreinte ou code. Rien de tout cela n''atteint ce serveur : il ne reçoit que la moitié publique de la clé et, à chaque connexion, une signature sur une question aléatoire valable une seule fois. Il n''y a donc ici aucun mot de passe à voler, ni aucune connexion réutilisable ailleurs. La création se fait dans le profil. Dans la liste, elle porte le nom de son trousseau — « Apple Mots de passe », « 1Password », « Windows Hello » — car c''est là qu''elle réside, et vous pouvez la renommer à tout moment. Votre mot de passe demeure et fonctionne toujours : en cas de perte d''un appareil, vous entrez avec lui et supprimez la clé dans le profil.'),
('es','help_passkey','En lugar de una contraseña puedes iniciar sesión con una clave de acceso: una clave que se crea en la zona segura de tu dispositivo y allí se queda. Se abre como abres tu dispositivo — con la cara, la huella o un código. Nada de eso llega a este servidor: solo recibe la mitad pública de la clave y, en cada inicio de sesión, una firma sobre una pregunta aleatoria válida una única vez. Así no hay aquí ninguna contraseña que robar ni ningún inicio de sesión reutilizable en otro sitio. Se crea en el perfil. En la lista aparece con el nombre de su llavero — «Contraseñas de Apple», «1Password», «Windows Hello» —, porque ahí es donde reside, y puedes renombrarla cuando quieras. Tu contraseña se mantiene y sigue funcionando: si pierdes un dispositivo, entras con ella y quitas la clave en el perfil.'),
('nl','help_passkey','In plaats van een wachtwoord kun je je aanmelden met een passkey: een sleutel die in het beveiligde deel van je apparaat ontstaat en daar blijft. Hij gaat open zoals je je apparaat opent — met gezicht, vingerafdruk of code. Niets daarvan bereikt deze server: die krijgt alleen de openbare helft van de sleutel en bij elke aanmelding een handtekening onder een willekeurige vraag die precies één keer geldt. Er is hier dus geen wachtwoord dat gestolen kan worden, en geen aanmelding die elders opnieuw te gebruiken is. Aanmaken doe je in je profiel. In de lijst staat hij onder de naam van zijn sleutelbos — „Apple Wachtwoorden", „1Password", „Windows Hello" — want daar ligt hij, en hernoemen kan altijd. Je wachtwoord blijft bestaan en werkt door: raak je een apparaat kwijt, dan kom je daarmee toch binnen en verwijder je de passkey in je profiel.'),
('it','help_passkey','Al posto di una password puoi accedere con una passkey: una chiave che nasce nell''area protetta del tuo dispositivo e lì resta. Si apre come apri il dispositivo — con il volto, l''impronta o un codice. Nulla di tutto ciò raggiunge questo server: riceve solo la metà pubblica della chiave e, a ogni accesso, una firma su una domanda casuale valida una sola volta. Non c''è quindi qui alcuna password da rubare, né un accesso riutilizzabile altrove. La crei nel profilo. Nell''elenco compare con il nome del suo portachiavi — «Password di Apple», «1Password», «Windows Hello» — perché è lì che risiede, e puoi rinominarla quando vuoi. La tua password resta e continua a funzionare: se perdi un dispositivo entri comunque con quella e rimuovi la passkey dal profilo.')
ON DUPLICATE KEY UPDATE value = value;
