-- The photo help text learned what the photo area can do now (v1.197-v1.203):
-- bursts, archive, tags, press picks, people, search, duplicates, OneDrive
-- previews. The outdated row is removed once in bootstrap (help_fotos_2026_08b),
-- then these take its place; earliest seed wins applies to the German text in
-- bootstrap the same way.
INSERT INTO translations (lang, tkey, value) VALUES
('en','help_fotos','Pictures for the public page and the band''s memory. On upload the application reads the capture date and location from the file and suggests the event — assigned only on click: singly, ticked in the bar, or as a whole origin folder at once. Those details are then removed from the stored file: a rehearsal room is often somebody''s home, and that should not travel with a published photo. Only originals straight from the device carry them at all; anything shared through a messenger lost them long ago. Pictures from the same source taken close together share one tile as a burst, with the count on it. From linked OneDrive folders only a preview is kept here — the original stays at OneDrive and is linked on the tile. Instead of deleting there is the archive: out of every gallery but not destroyed, brought back with one click. Tags, the press picks for handing out, and people named by hand make pictures findable; the search field looks through caption, origin, event, tag and person — including the archive. Duplicate files are found by checksum on the cleanup page in the settings.'),
('nl','help_fotos','Foto''s voor de openbare pagina en het geheugen van de band. Bij het uploaden leest de toepassing opnamedatum en -locatie uit het bestand en stelt daarmee de afspraak voor — gekoppeld wordt pas op een klik: per stuk, aangevinkt via de balk, of meteen als hele herkomstmap. Daarna worden die gegevens uit het opgeslagen bestand verwijderd: een oefenruimte is vaak een privéadres, en dat hoort niet mee te gaan met een gepubliceerde foto. Alleen originelen rechtstreeks van het apparaat hebben ze; wat via een messenger is gedeeld, is ze allang kwijt. Foto''s uit dezelfde bron die kort na elkaar zijn gemaakt, delen als reeks één tegel met een aantal erop. Uit gekoppelde OneDrive-mappen ligt hier alleen een voorbeeld — het origineel blijft bij OneDrive en is op de tegel gelinkt. In plaats van verwijderen is er het archief: uit elke galerij, maar niet vernietigd, met één klik terug te halen. Trefwoorden, de persselectie om uit te geven en met de hand benoemde personen maken foto''s vindbaar; het zoekveld zoekt in beschrijving, herkomst, afspraak, trefwoord en persoon — ook in het archief. Dubbele bestanden vindt het opruimen in de instellingen aan de hand van een controlesom.'),
('fr','help_fotos','Des images pour la page publique et pour la mémoire du groupe. Au téléversement, l''application lit la date et le lieu de prise de vue dans le fichier et propose la date correspondante — l''association ne se fait qu''au clic : une par une, cochées dans la barre, ou d''un coup par dossier d''origine entier. Ces informations sont ensuite retirées du fichier conservé : un local de répétition est souvent un domicile, et cela n''a pas à partir avec une photo publiée. Seuls les originaux venant directement de l''appareil les portent ; ce qui a été partagé par messagerie les a perdues depuis longtemps. Les photos d''une même source prises à peu d''intervalle partagent une tuile en série, avec leur nombre. Des dossiers OneDrive liés, seul un aperçu est conservé ici — l''original reste chez OneDrive et est lié sur la tuile. Au lieu de supprimer, il y a les archives : retirée de chaque galerie mais pas détruite, une photo revient en un clic. Les mots-clés, la sélection presse à diffuser et les personnes nommées à la main rendent les photos trouvables ; le champ de recherche parcourt description, origine, date, mot-clé et personne — archives comprises. Les fichiers en double sont trouvés par somme de contrôle sur la page de nettoyage des réglages.'),
('es','help_fotos','Fotos para la página pública y para la memoria de la banda. Al subir, la aplicación lee del archivo la fecha y el lugar de captura y propone la cita — se asigna solo con un clic: una a una, marcadas en la barra, o de golpe por carpeta de origen entera. Después esos datos se eliminan del archivo guardado: un local de ensayo suele ser un domicilio, y eso no debe viajar con una foto publicada. Solo los originales directos del aparato los llevan; lo compartido por mensajería los perdió hace tiempo. Las fotos de la misma fuente tomadas con poco intervalo comparten una tesela como serie, con su número. De las carpetas de OneDrive vinculadas aquí solo queda una vista previa — el original permanece en OneDrive y está enlazado en la tesela. En lugar de borrar existe el archivo: fuera de todas las galerías pero no destruida, una foto vuelve con un clic. Las etiquetas, la selección de prensa para entregar y las personas nombradas a mano hacen que las fotos se encuentren; el campo de búsqueda recorre descripción, origen, cita, etiqueta y persona — incluido el archivo. Los archivos duplicados se encuentran por suma de verificación en la página de limpieza de los ajustes.'),
('it','help_fotos','Foto per la pagina pubblica e per la memoria della band. Al caricamento l''applicazione legge dal file data e luogo dello scatto e propone la data corrispondente — l''assegnazione avviene solo con un clic: una alla volta, spuntate nella barra, o in un colpo per intera cartella di origine. Quei dati vengono poi rimossi dal file salvato: una sala prove è spesso un domicilio, e non deve viaggiare con una foto pubblicata. Solo gli originali diretti dal dispositivo li portano; ciò che è passato per un messenger li ha persi da tempo. Le foto della stessa fonte scattate a breve distanza condividono una tessera come serie, con il numero sopra. Dalle cartelle OneDrive collegate qui resta solo un''anteprima — l''originale rimane su OneDrive ed è collegato sulla tessera. Invece di cancellare c''è l''archivio: fuori da ogni galleria ma non distrutta, una foto torna con un clic. Le parole chiave, la selezione stampa da consegnare e le persone indicate a mano rendono le foto trovabili; il campo di ricerca cerca in descrizione, origine, data, parola chiave e persona — archivio compreso. I file doppi si trovano tramite somma di controllo nella pagina di pulizia delle impostazioni.')
ON DUPLICATE KEY UPDATE value = value;
